In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',None)

In [4]:
train = pd.read_csv("../data/raw/train_data.csv")
test = pd.read_csv("../data/raw/test_data.csv")
sample = pd.read_csv("../data/raw/sample_submission.csv")

In [5]:
train.shape

(4020, 13)

In [6]:
train.head()

,CustomerID,Surname,NetworkScore,Region,Gender,Age,Tenure,MonthlyCharge,NumOfProducts,HasInternetService,IsActiveMember,EstimatedMonthlyUsage,Exited
0,4971,Moreno,25.0,South,Female,26.0,11,134.20,1,0,1.0,NaN,1
1,2858,Bell,68.0,North,Female,60.0,17,25.72,3,1,1.0,533.40,0
2,5794,Baker,34.0,North,Male,28.0,7,131.03,2,0,0.0,509.04,0
3,3996,Jackson,13.0,South,Male,65.0,2,64.27,3,0,1.0,246.48,0
4,2680,Craig,50.0,East,Female,60.0,16,41.26,3,1,1.0,902.28,1

In [7]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             4020 non-null   int64
 1   Surname                4020 non-null   str
 2   NetworkScore           3821 non-null   float64
 3   Region                 4020 non-null   str
 4   Gender                 4020 non-null   str
 5   Age                    3812 non-null   float64
 6   Tenure                 4020 non-null   int64
 7   MonthlyCharge          4020 non-null   float64
 8   NumOfProducts          4020 non-null   int64
 9   HasInternetService     4020 non-null   int64
 10  IsActiveMember         3822 non-null   float64
 11  EstimatedMonthlyUsage  3823 non-null   float64
 12  Exited                 4020 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 408.4 KB

In [8]:
train.describe()

,CustomerID,NetworkScore,Age,Tenure,MonthlyCharge,NumOfProducts,HasInternetService,IsActiveMember,EstimatedMonthlyUsage,Exited
count,4020.000000,3821.000000,3812.000000,4020.000000,4020.000000,4020.000000,4020.000000,3822.000000,3823.000000,4020.000000
mean,2985.333333,51.172468,43.961962,10.092786,109.808458,2.479104,0.507463,0.490581,548.373380,0.485572
std,1729.892759,28.975876,15.300416,6.076202,52.417745,1.122198,0.500006,0.499977,258.494824,0.499854
min,3.000000,1.000000,18.000000,0.000000,20.030000,1.000000,0.000000,0.000000,100.090000,0.000000
25%,1481.750000,26.000000,31.000000,5.000000,64.652500,1.000000,0.000000,0.000000,329.485000,0.000000
50%,2981.500000,52.000000,44.000000,10.000000,109.335000,2.000000,1.000000,0.000000,546.250000,0.000000
75%,4467.500000,77.000000,57.000000,15.000000,155.782500,3.000000,1.000000,1.000000,772.725000,1.000000
max,6000.000000,100.000000,70.000000,20.000000,199.960000,4.000000,1.000000,1.000000,999.820000,1.000000

In [ ]:
train.isnull().sum()

NameError: name 'missing' is not defined

In [11]:
missing = train.isnull().sum()

missing_percent = (missing / len(train))*100

pd.DataFrame({
    'Missing_Count':missing,
    'Missing_Percentage':missing_percent
}).sort_values(
    by='Missing_Percentage',
    ascending=False
)

                       Missing_Count  Missing_Percentage
Age                              208            5.174129
NetworkScore                     199            4.950249
IsActiveMember                   198            4.925373
EstimatedMonthlyUsage            197            4.900498
CustomerID                         0            0.000000
Gender                             0            0.000000
Region                             0            0.000000
Surname                            0            0.000000
Tenure                             0            0.000000
NumOfProducts                      0            0.000000
MonthlyCharge                      0            0.000000
HasInternetService                 0            0.000000
Exited                             0            0.000000

In [12]:
train['NetworkScore'] = train['NetworkScore'].fillna(
    train['NetworkScore'].median()
)

train['Age'] = train['Age'].fillna(
    train['Age'].median()
)

train['IsActiveMember'] = train['IsActiveMember'].fillna(
    train['IsActiveMember'].mode()[0]
)

train['EstimatedMonthlyUsage'] = \
train['EstimatedMonthlyUsage'].fillna(
train['EstimatedMonthlyUsage'].median()
)

In [13]:
train.isnull().sum()

CustomerID               0
Surname                  0
NetworkScore             0
Region                   0
Gender                   0
Age                      0
Tenure                   0
MonthlyCharge            0
NumOfProducts            0
HasInternetService       0
IsActiveMember           0
EstimatedMonthlyUsage    0
Exited                   0
dtype: int64

In [14]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             4020 non-null   int64
 1   Surname                4020 non-null   str
 2   NetworkScore           4020 non-null   float64
 3   Region                 4020 non-null   str
 4   Gender                 4020 non-null   str
 5   Age                    4020 non-null   float64
 6   Tenure                 4020 non-null   int64
 7   MonthlyCharge          4020 non-null   float64
 8   NumOfProducts          4020 non-null   int64
 9   HasInternetService     4020 non-null   int64
 10  IsActiveMember         4020 non-null   float64
 11  EstimatedMonthlyUsage  4020 non-null   float64
 12  Exited                 4020 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 408.4 KB

In [15]:
numeric_cols = train.select_dtypes(
    include=['int64','float64']
).columns

categorical_cols = train.select_dtypes(
    include='object'
).columns

print("Numeric")
print(numeric_cols)

print("\nCategorical")
print(categorical_cols)

Numeric
Index(['CustomerID', 'NetworkScore', 'Age', 'Tenure', 'MonthlyCharge',
       'NumOfProducts', 'HasInternetService', 'IsActiveMember',
       'EstimatedMonthlyUsage', 'Exited'],
      dtype='str')

Categorical
Index(['Surname', 'Region', 'Gender'], dtype='str')

C:\Users\shlok\AppData\Local\Temp\ipykernel_12820\2977137476.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = train.select_dtypes(

In [16]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CustomerID             4020 non-null   int64
 1   Surname                4020 non-null   str
 2   NetworkScore           4020 non-null   float64
 3   Region                 4020 non-null   str
 4   Gender                 4020 non-null   str
 5   Age                    4020 non-null   float64
 6   Tenure                 4020 non-null   int64
 7   MonthlyCharge          4020 non-null   float64
 8   NumOfProducts          4020 non-null   int64
 9   HasInternetService     4020 non-null   int64
 10  IsActiveMember         4020 non-null   float64
 11  EstimatedMonthlyUsage  4020 non-null   float64
 12  Exited                 4020 non-null   int64
dtypes: float64(5), int64(5), str(3)
memory usage: 408.4 KB

In [17]:
train['Exited'].value_counts()

Exited
0    2068
1    1952
Name: count, dtype: int64